(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.Engine=factory();})(typeof self!=='undefined'?self:this,function(){'use strict';
const PRIORITY=['EUR','GBP','AUD','NZD','USD','CAD','CHF','JPY'];
const SUPPORTED_ACCOUNT_CURRENCIES=['USD','EUR','GBP','CAD','AUD','NZD','CHF','JPY'];
const INSTRUMENTS={};
function fx(symbol,base,quote,js){INSTRUMENTS[symbol]={symbol,type:'forex',baseCurrency:base,quoteCurrency:quote,contractSize:100000,pipSize:js?0.01:0.0001,pointSize:js?0.001:0.00001,digits:js?3:5,minLot:.01,maxLot:100,lotStep:.01};}
['EURUSD','GBPUSD','USDCHF','USDCAD','AUDUSD','NZDUSD'].forEach(s=>fx(s,s.slice(0,3),s.slice(3)));fx('USDJPY','USD','JPY',1);
['EURGBP','EURCHF','EURCAD','EURAUD','EURNZD'].forEach(s=>fx(s,s.slice(0,3),s.slice(3)));fx('EURJPY','EUR','JPY',1);
['GBPCHF','GBPCAD','GBPAUD','GBPNZD'].forEach(s=>fx(s,'GBP',s.slice(3)));fx('GBPJPY','GBP','JPY',1);
['AUDCHF','AUDCAD','AUDNZD'].forEach(s=>fx(s,'AUD',s.slice(3)));fx('AUDJPY','AUD','JPY',1);
['NZDCHF','NZDCAD'].forEach(s=>fx(s,'NZD',s.slice(3)));fx('NZDJPY','NZD','JPY',1);
fx('CADCHF','CAD','CHF');fx('CADJPY','CAD','JPY',1);fx('CHFJPY','CHF','JPY',1);
INSTRUMENTS.XAUUSD={symbol:'XAUUSD',type:'metal',baseCurrency:'XAU',quoteCurrency:'USD',contractSize:100,tickSize:.01,pointSize:.01,digits:2,minLot:.01,maxLot:50,lotStep:.01,isConfigAssumed:true};
class EngineError extends Error{}
function getInstrument(symbol){if(!INSTRUMENTS[symbol])throw new EngineError('Unknown instrument: '+symbol);return INSTRUMENTS[symbol];}
function resolveConversion(quote,account){if(quote===account)return null;const qi=PRIORITY.indexOf(quote),ai=PRIORITY.indexOf(account);if(qi<0||ai<0)throw new EngineError('No standard FX conversion known for '+quote+'/'+account);return qi<ai?{pairSymbol:quote+account,invert:false}:{pairSymbol:account+quote,invert:true};}
function pipValuePerLot(symbol,accountCurrency,rateOrTable){const i=getInstrument(symbol);const size=i.type==='forex'?i.pipSize:i.tickSize;const quoteValue=size*i.contractSize;const c=resolveConversion(i.quoteCurrency,accountCurrency);if(!c)return{pipValuePerLot:quoteValue,conversion:null,pipSize:size,movementLabel:i.type==='forex'?'pip':'tick'};let rate=rateOrTable;if(rate&&typeof rate==='object')rate=rate[c.pairSymbol];if(!Number.isFinite(rate)||rate<=0)throw new EngineError('A valid '+c.pairSymbol+' rate is required to convert '+i.quoteCurrency+' to '+accountCurrency+'.');return{pipValuePerLot:quoteValue*(c.invert?1/rate:rate),conversion:{...c,rateUsed:rate,rateSource:rateOrTable&&typeof rateOrTable==='object'?'rates-table':'manual'},pipSize:size,movementLabel:i.type==='forex'?'pip':'tick'};}
function calculatePosition({symbol,accountCurrency,accountBalance,riskPercent,stopLossPips,takeProfitPips,conversionRate,rateIsLive}){if(!SUPPORTED_ACCOUNT_CURRENCIES.includes(accountCurrency))throw new EngineError('Unsupported account currency: '+accountCurrency+'.');if(!(accountBalance>0))throw new EngineError('Account balance must be greater than 0.');if(!(riskPercent>0))throw new EngineError('Risk % must be greater than 0.');if(!(stopLossPips>0))throw new EngineError('Stop loss must be greater than 0.');const i=getInstrument(symbol),v=pipValuePerLot(symbol,accountCurrency,conversionRate),riskAmount=accountBalance*riskPercent/100,rawLot=riskAmount/(stopLossPips*v.pipValuePerLot),steps=Math.floor(rawLot/i.lotStep+1e-9),recommendedLot=Math.round(steps*i.lotStep*1e8)/1e8,belowMin=recommendedLot<i.minLot,clamped=recommendedLot>i.maxLot,finalLot=belowMin?0:Math.min(recommendedLot,i.maxLot),potentialLoss=finalLot*stopLossPips*v.pipValuePerLot,potentialProfit=takeProfitPips>0?finalLot*takeProfitPips*v.pipValuePerLot:null,riskReward=takeProfitPips>0?takeProfitPips/stopLossPips:null;return{symbol,instrumentType:i.type,accountCurrency,accountBalance,riskPercent,riskAmount,stopLossPips,takeProfitPips,pipSize:v.pipSize,pointSize:i.pointSize,tickSize:i.tickSize||null,movementLabel:v.movementLabel,pipValuePerLot:v.pipValuePerLot,rawLotSize:rawLot,recommendedLot:finalLot,belowMinLot:belowMin,clampedToMax:clamped,minLot:i.minLot,maxLot:i.maxLot,lotStep:i.lotStep,potentialLoss,potentialProfit,riskReward,conversion:v.conversion,rateIsLive:!!rateIsLive,isConfigAssumed:!!i.isConfigAssumed};}
return{INSTRUMENTS,PRIORITY,CURRENCY_PRIORITY:PRIORITY,SUPPORTED_ACCOUNT_CURRENCIES,EngineError,getInstrument,listInstruments:()=>Object.keys(INSTRUMENTS),resolveConversion,pipValuePerLot,calculatePosition};});
